services:
  db:
    image: postgres:15.4-alpine3.18
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: finance_db
    volumes:
      - db_data:/var/lib/postgresql/data

  modules:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/finance_db
      PORT: 5000
      FLASK_APP: modules
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  db_data: