version: '3'

services:
  lab2-app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      FLASK_APP: modules
      PORT: "5000"
    ports:
      - "5000:5000"